AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates ECR repository

Parameters:
  Name:
    Description: Repository name
    Type: String

  ProjectName:
    Description: Project or repository name used to identify created AWS resources
    Type: String

Resources:
  Repo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref Name
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName

  AuthRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${Name}-auth
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName
