AWSTemplateFormatVersion: '2010-09-09'

Description: >
  This template creates load balancer for services running in ECS cluster

Parameters:
  ProjectName:
    Type: String
    Description: Project or repository name used to identify created AWS resources

  SubnetOne:
    Type: String

  SubnetTwo:
    Type: String

  SG:
    Type: String
    Description: Security group ID

Resources:
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404
            ContentType: text/plain
            MessageBody: Not Found
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !Ref SubnetOne
        - !Ref SubnetTwo
      SecurityGroups: 
        - !Ref SG
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: stack
          Value: !Ref AWS::StackName
      
